version: '3.3'

services:
  rabbitmq:
    image: 'rabbitmq:3'
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks: 
      - defaultNetwork   

  email-ms:
    container_name: email-ms
    build:
      target: production
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    networks: 
      - defaultNetwork
    restart: unless-stopped    

networks: 
  defaultNetwork:
    driver: bridge            
